[package]
name = "cetzpingus"
version = "0.1.0"
entrypoint = "pingus.typ"
license = "MIT"
authors = [@leyan]
repository = "https://github.com/leyan/cetzpenguins"
description = "Penguins in Typst drawn with CeTZ"